#! /usr/bin/env bash

 echo "== create bucket"

#Check for bucket name
if [ -z "$1" ]; then
    echo "There need too be a bucket name e.g ../bucket zxax-demo-one"
    exit 1
fi

BUCKET_NAME=$1

aws s3api create-bucket --bucket $BUCKET_NAME \
--create-bucket-configuration="LocationConstraint=ca-central-1" \
--query Location \
--output text