#! /usr/bin/env bash


 echo "== list objects"

#Check for bucket name
if [ -z "$1" ]; then
    echo "There need too be a bucket name e.g ../bucket zxax-demo-one"
    exit 1
fi

BUCKET_NAME=$1

aws s3api list-objects-v2 --bucket $BUCKET_NAME 

