#! /usr/bin/env bash

echo "== put object"

#Check for bucket name
if [ -z "$1" ]; then
    echo "There need too be a bucket name e.g ../bucket zxax-demo-one"
    exit 1
fi



if [ -z "$2" ]; then
    echo "There need too be a filename e.g ../bucket zxax-demo-one filename"
    exit 1
fi
 
BUCKET_NAME=$1
FILENAME=$2

OBJECT_KEY=$(basename "$FILENAME")

 aws s3api put-object --bucket $BUCKET_NAME --body $FILENAME --key $OBJECT_KEY