#! /usr/bin/env bash

#exit immediately if any command returns a non-zero status
set -e

#Check for bucket name
if [ -z "$1" ]; then
    echo "There need too be a bucket name e.g ../bucket zxax-demo-one"
    exit 1
fi


#Check for filename prefix
if [ -z "$2" ]; then
    echo "There need too be a filename prefix e.g ../bucket zxax-demo-one my-filename-prefix"
    exit 1
fi
 
BUCKET_NAME=$1
FILENAME_PREFIX=$2



#where we will store the files
OUTPUT_DIR="/tmp/s3-bash-scripts"

#let's create the output folder
mkdir -p $OUTPUT_DIR

#remove folder if already exists
rm -r $OUTPUT_DIR

#generate a random number
#to dtermine how many files to create

NUM_FILES=$((RANDOM % 6 + 5))


for ((i=1; i<=NUM_FILES; i++))do 
#generate a random file name
FILENAME=$OUTPUT_DIR/$FILENAME_PREFIX_$i.txt

#generate random data to put in the file
dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null

done

tree $OUTPUT_DIR

aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files 